package com.u1.slicer.data

import android.content.Context
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * Regression test for G-code save truncation bug.
 *
 * When saving a shorter G-code file over a longer one via ContentResolver,
 * the old tail data must be truncated. Without "wt" mode in openOutputStream(),
 * some DocumentsProviders leave the old data intact, producing corrupted files
 * with two G-code programs concatenated.
 */
@RunWith(AndroidJUnit4::class)
class GcodeSaveTruncationTest {

    private val context: Context get() = InstrumentationRegistry.getInstrumentation().targetContext

    @Test
    fun saveGcode_shorterOverLonger_oldDataTruncated() {
        // Simulate the bug: a long G-code file is saved, then a shorter one overwrites it.
        // The file must contain ONLY the shorter content afterward.

        val longGcode = buildString {
            appendLine("; HEADER_BLOCK_START")
            appendLine("; generated by test - LONG file")
            appendLine("; total layer number: 239")
            appendLine("; HEADER_BLOCK_END")
            repeat(10_000) { i ->
                appendLine("G1 X${i % 270}.000 Y${i % 270}.000 E0.05 ; layer line $i")
            }
            appendLine("; estimated printing time (normal mode) = 35m 0s")
            appendLine("; CONFIG_BLOCK_END")
        }

        val shortGcode = buildString {
            appendLine("; HEADER_BLOCK_START")
            appendLine("; generated by test - SHORT file")
            appendLine("; total layer number: 49")
            appendLine("; HEADER_BLOCK_END")
            repeat(100) { i ->
                appendLine("G1 X${i % 270}.000 Y${i % 270}.000 E0.05 ; layer line $i")
            }
            appendLine("; estimated printing time (normal mode) = 12m 0s")
            appendLine("; CONFIG_BLOCK_END")
        }

        // Verify precondition: short is actually shorter than long
        assert(shortGcode.length < longGcode.length) {
            "Test setup: short (${shortGcode.length}) must be < long (${longGcode.length})"
        }

        val outputFile = File(context.cacheDir, "truncation_test_output.gcode")
        try {
            // Step 1: Write long G-code
            outputFile.writeText(longGcode)
            assertEquals("Long file written", longGcode.length.toLong(), outputFile.length())

            // Step 2: Overwrite with short G-code using the SAME approach as saveGcodeTo()
            // This uses FileOutputStream which always truncates (the bug was with ContentResolver).
            // We test the contract: after save, file must equal the new content exactly.
            val shortBytes = shortGcode.toByteArray()
            outputFile.outputStream().use { out ->
                out.write(shortBytes)
            }

            // Step 3: Verify file contains ONLY the short content
            val savedContent = outputFile.readText()
            assertEquals(
                "Saved file size must equal short G-code size (no stale tail data)",
                shortGcode.length.toLong(),
                outputFile.length()
            )
            assertEquals(
                "Saved content must exactly match short G-code",
                shortGcode,
                savedContent
            )

            // Step 4: Verify no traces of the long file remain
            assertFalse(
                "File must not contain long file's layer count",
                savedContent.contains("total layer number: 239")
            )
            assertFalse(
                "File must not contain long file's marker",
                savedContent.contains("LONG file")
            )
            assertEquals(
                "File must have exactly one HEADER_BLOCK_START",
                1,
                savedContent.split("HEADER_BLOCK_START").size - 1
            )
            assertEquals(
                "File must have exactly one estimated printing time",
                1,
                savedContent.split("estimated printing time").size - 1
            )
        } finally {
            outputFile.delete()
        }
    }

    @Test
    fun saveGcode_contentResolverWtMode_truncatesFile() {
        // Test the actual ContentResolver "wt" mode behavior used by saveGcodeTo()
        val longContent = "LONG CONTENT\n".repeat(1000)
        val shortContent = "SHORT\n".repeat(10)

        val outputFile = File(context.cacheDir, "truncation_cr_test.gcode")
        try {
            // Write long file first
            outputFile.writeText(longContent)

            // Now use ContentResolver with "wt" mode via a file:// URI
            // Note: file:// URIs work with ContentResolver on app-private files
            val uri = android.net.Uri.fromFile(outputFile)
            context.contentResolver.openOutputStream(uri, "wt")?.use { out ->
                out.write(shortContent.toByteArray())
            }

            val result = outputFile.readText()
            assertEquals(
                "ContentResolver 'wt' mode must truncate: file should equal short content",
                shortContent,
                result
            )
            assertEquals(
                "File length must match short content length",
                shortContent.length.toLong(),
                outputFile.length()
            )
        } finally {
            outputFile.delete()
        }
    }
}
