/**
 * Android replacement for glad/gles2.h
 *
 * On Android, GLES3 functions are linked directly via NDK — no dynamic
 * loading needed. This replaces glad's function-pointer machinery with
 * direct NDK headers.
 *
 * Original file: glad gles2 loader (generated by glad 2.0.4)
 * Replaced for: Android NDK / OpenGL ES 3.0 direct linkage
 */
#ifndef GLAD_GLES2_H_
#define GLAD_GLES2_H_

#include <GLES3/gl3.h>
#include <GLES3/gl3ext.h>

#ifndef GLAD_API_CALL
#define GLAD_API_CALL
#endif

#ifdef __cplusplus
extern "C" {
#endif

int gladLoaderLoadGLES2(void);
void gladLoaderUnloadGLES2(void);

#ifdef __cplusplus
}
#endif

#endif /* GLAD_GLES2_H_ */
