package com.u1.slicer.gcode

import org.junit.Assert.*
import org.junit.Test
import java.io.File

class ExcludeObjectParserTest {

    private fun parseLines(vararg lines: String): List<ExcludeObjectInfo> {
        val tmp = File.createTempFile("gcode", ".gcode")
        tmp.deleteOnExit()
        tmp.writeText(lines.joinToString("\n"))
        return parseExcludeObjects(tmp.absolutePath)
    }

    @Test
    fun `parses name center and polygon from single define line`() {
        val result = parseLines(
            "EXCLUDE_OBJECT_DEFINE NAME=cube_1 CENTER=100.0,50.0 POLYGON=[[80.0,30.0],[120.0,30.0],[120.0,70.0],[80.0,70.0]]"
        )
        assertEquals(1, result.size)
        assertEquals("cube_1", result[0].name)
        assertEquals(100.0f, result[0].center.first, 0.01f)
        assertEquals(50.0f, result[0].center.second, 0.01f)
        assertEquals(4, result[0].polygon.size)
        assertEquals(80.0f, result[0].polygon[0].first, 0.01f)
        assertEquals(30.0f, result[0].polygon[0].second, 0.01f)
    }

    @Test
    fun `handles missing polygon gracefully returns empty polygon list`() {
        val result = parseLines("EXCLUDE_OBJECT_DEFINE NAME=obj_1 CENTER=135.0,135.0")
        assertEquals(1, result.size)
        assertEquals("obj_1", result[0].name)
        assertEquals(135.0f, result[0].center.first, 0.01f)
        assertTrue(result[0].polygon.isEmpty())
    }

    @Test
    fun `parses multiple define lines in order`() {
        val result = parseLines(
            "EXCLUDE_OBJECT_DEFINE NAME=obj_a CENTER=50.0,50.0 POLYGON=[[40.0,40.0],[60.0,40.0],[60.0,60.0],[40.0,60.0]]",
            "EXCLUDE_OBJECT_DEFINE NAME=obj_b CENTER=200.0,200.0 POLYGON=[[190.0,190.0],[210.0,190.0],[210.0,210.0],[190.0,210.0]]"
        )
        assertEquals(2, result.size)
        assertEquals("obj_a", result[0].name)
        assertEquals("obj_b", result[1].name)
    }

    @Test
    fun `returns empty list when no define lines present`() {
        val result = parseLines(
            "; generated by OrcaSlicer",
            "G28 ; home all axes",
            "G1 X100 Y100 F3000"
        )
        assertTrue(result.isEmpty())
    }

    @Test
    fun `ignores EXCLUDE_OBJECT_START and EXCLUDE_OBJECT_END lines`() {
        val result = parseLines(
            "EXCLUDE_OBJECT_START NAME=cube_1",
            "EXCLUDE_OBJECT_DEFINE NAME=cube_1 CENTER=100.0,100.0",
            "EXCLUDE_OBJECT_END NAME=cube_1"
        )
        assertEquals(1, result.size)
        assertEquals("cube_1", result[0].name)
    }
}
