package com.u1.slicer.gcode

import org.junit.Assert.*
import org.junit.Test
import java.io.File

class GcodeToolRemapperTest {

    private val identity = mapOf(0 to 0, 1 to 1)
    private val shift2 = mapOf(0 to 2, 1 to 3)   // E3+E4 scenario

    // ── remapLine ──────────────────────────────────────────────────────────────

    @Test
    fun `standalone T0 remapped to T2`() {
        assertEquals("T2", GcodeToolRemapper.remapLine("T0", shift2))
    }

    @Test
    fun `standalone T1 remapped to T3`() {
        assertEquals("T3", GcodeToolRemapper.remapLine("T1", shift2))
    }

    @Test
    fun `standalone T0 with comment remapped`() {
        assertEquals("T2", GcodeToolRemapper.remapLine("T0 ; change tool", shift2))
    }

    @Test
    fun `standalone T with identity map unchanged`() {
        assertEquals("T0", GcodeToolRemapper.remapLine("T0", identity))
    }

    @Test
    fun `unknown compact index left unchanged`() {
        // T5 not in map — leave as-is
        assertEquals("T5", GcodeToolRemapper.remapLine("T5", shift2))
    }

    @Test
    fun `M104 T0 remapped`() {
        val result = GcodeToolRemapper.remapLine("M104 S210 T0", shift2)
        assertEquals("M104 S210 T2", result)
    }

    @Test
    fun `M109 T1 remapped`() {
        val result = GcodeToolRemapper.remapLine("M109 S210 T1", shift2)
        assertEquals("M109 S210 T3", result)
    }

    @Test
    fun `M104 T0 with leading T param remapped`() {
        val result = GcodeToolRemapper.remapLine("M104 T0 S210", shift2)
        assertEquals("M104 T2 S210", result)
    }

    @Test
    fun `unrelated line not modified`() {
        val line = "G1 X10 Y20 E1.5 F3000"
        assertEquals(line, GcodeToolRemapper.remapLine(line, shift2))
    }

    @Test
    fun `G28 home not modified`() {
        val line = "G28 ; home"
        assertEquals(line, GcodeToolRemapper.remapLine(line, shift2))
    }

    // ── remap (file-level) ────────────────────────────────────────────────────

    @Test
    fun `remap file rewrites tool changes and temperatures`() {
        val gcode = listOf(
            "; generated by Snapmaker Orca",
            "G28",
            "M104 S210 T0",
            "T0",
            "G1 X0 Y0",
            "M109 S210 T0",
            "T1",
            "M104 S215 T1",
        )
        val tmp = File.createTempFile("test", ".gcode")
        tmp.writeText(gcode.joinToString("\n"))

        GcodeToolRemapper.remap(tmp.absolutePath, listOf(2, 3))

        val lines = tmp.readLines()
        tmp.delete()

        assertEquals("; generated by Snapmaker Orca", lines[0])
        assertEquals("G28", lines[1])
        assertEquals("M104 S210 T2", lines[2])
        assertEquals("T2", lines[3])
        assertEquals("G1 X0 Y0", lines[4])
        assertEquals("M109 S210 T2", lines[5])
        assertEquals("T3", lines[6])
        assertEquals("M104 S215 T3", lines[7])
    }

    @Test
    fun `remap leaves no trace of original compact tool indices`() {
        val gcode = "T0\nT1\nM104 S210 T0\nM109 S215 T1\nG1 X0\n"
        val tmp = File.createTempFile("test", ".gcode")
        tmp.writeText(gcode)

        GcodeToolRemapper.remap(tmp.absolutePath, listOf(2, 3))

        val result = tmp.readText()
        tmp.delete()

        // No standalone T0 or T1 should remain
        assertTrue(GcodeValidator.lacksToolChanges(result, "T0", "T1"))
        // T2 and T3 must be present
        assertTrue(GcodeValidator.hasToolChanges(result, "T2", "T3"))
    }

    @Test
    fun `remap with identity mapping produces correct output`() {
        val gcode = "T0\nT1\nM104 S210 T0\n"
        val tmp = File.createTempFile("test", ".gcode")
        tmp.writeText(gcode)

        GcodeToolRemapper.remap(tmp.absolutePath, listOf(0, 1))

        val result = tmp.readText()
        tmp.delete()

        assertTrue(result.contains("T0"))
        assertTrue(result.contains("T1"))
        assertFalse(result.contains("T2"))
    }
}
