package com.u1.slicer.bambu

import org.json.JSONObject
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.util.zip.ZipFile
import com.u1.slicer.slice.SlicerTarget

class BambuProjectWriterTest {

    @get:Rule
    val tmp = TemporaryFolder()

    @Test
    fun `writer packages every supported bambu identity and machine filament profile`() {
        val expected = mapOf(
            SlicerTarget.BambuX1C to Triple("BL-P001", "Bambu Lab X1 Carbon", "Bambu PLA Basic @BBL X1C"),
            SlicerTarget.BambuX1E to Triple("C13", "Bambu Lab X1E", "Bambu PLA Basic @BBL X1C"),
            SlicerTarget.BambuP1S to Triple("C12", "Bambu Lab P1S", "Bambu PLA Basic @BBL X1C"),
            SlicerTarget.BambuP1P to Triple("C11", "Bambu Lab P1P", "Bambu PLA Basic @BBL X1"),
            SlicerTarget.BambuP2S to Triple("GM049", "Bambu Lab P2S", "Bambu PLA Basic @BBL P2S"),
            SlicerTarget.BambuA1 to Triple("N2S", "Bambu Lab A1", "Bambu PLA Basic @BBL A1"),
            SlicerTarget.BambuA1Mini to Triple("N1", "Bambu Lab A1 mini", "Bambu PLA Basic @BBL A1M"),
            SlicerTarget.BambuH2D to Triple("O1D", "Bambu Lab H2D", "Bambu PLA Basic @BBL H2D"),
        )

        expected.forEach { (target, identity) ->
            val gcode = File(tmp.root, "${target.name}.gcode").apply { writeText("G28\n") }
            val out = File(tmp.root, "${target.name}.gcode.3mf")
            BambuProjectWriter.writeSinglePlateProject(
                outputFile = out,
                gcodeFile = gcode,
                modelName = target.name,
                plateId = 1,
                filamentColours = listOf("#FFFFFF"),
                filamentTypes = listOf("PLA"),
                target = target,
            )

            ZipFile(out).use { zip ->
                val settings = JSONObject(
                    zip.getInputStream(zip.getEntry("Metadata/project_settings.config")).reader().readText(),
                )
                assertEquals(identity.first, settings.getString("printer_model_id"))
                assertEquals(identity.second, settings.getString("printer_model"))
                assertEquals(
                    identity.third,
                    settings.getJSONArray("filament_settings_id").getString(0),
                )
            }
        }
    }

    @Test
    fun `h2d writer counts standard nozzle volumes per logical nozzle`() {
        val gcode = tmp.newFile("h2d-nozzle-stats.gcode").apply { writeText("G28\n") }
        val out = File(tmp.root, "h2d-nozzle-stats.gcode.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "dual",
            plateId = 1,
            filamentColours = listOf("#111111", "#222222", "#333333"),
            filamentTypes = listOf("PLA", "PETG", "ABS"),
            target = SlicerTarget.BambuH2D,
            filamentNozzleMap = listOf(2, 2, 1),
        )

        ZipFile(out).use { zip ->
            val settings = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/project_settings.config")).reader().readText(),
            )
            assertEquals("Standard#1", settings.getJSONArray("extruder_nozzle_stats").getString(0))
            assertEquals("Standard#2", settings.getJSONArray("extruder_nozzle_stats").getString(1))
            assertEquals(7, settings.getJSONArray("nozzle_type").length())
            assertEquals("hardened_steel", settings.getJSONArray("nozzle_type").getString(6))
            assertEquals(130, settings.getJSONArray("nozzle_volume").getInt(0))
            assertEquals(145, settings.getJSONArray("nozzle_volume").getInt(3))
            assertEquals(7, settings.getJSONArray("printer_extruder_variant").length())
            assertEquals(2, settings.getJSONArray("nozzle_volume_type").length())
        }
    }

    @Test
    fun `writer creates sendable project with expected entries`() {
        val gcode = tmp.newFile("plate_1.gcode").apply {
            writeText("; generated by test\nG28\n")
        }
        val out = File(tmp.root, "a1-mini-project.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "cube",
            plateId = 1,
            filamentColours = listOf("#FFFFFF"),
            filamentTypes = listOf("PLA"),
        )

        ZipFile(out).use { zip ->
            assertNotNull(zip.getEntry("3D/3dmodel.model"))
            assertNotNull(zip.getEntry("3D/_rels/3dmodel.model.rels"))
            assertNotNull(zip.getEntry("3D/Objects/object_1.model"))
            assertNotNull(zip.getEntry("Metadata/model_settings.config"))
            assertNotNull(zip.getEntry("Metadata/cut_information.xml"))
            assertNotNull(zip.getEntry("Metadata/_rels/model_settings.config.rels"))
            assertNotNull(zip.getEntry("Metadata/project_settings.config"))
            assertNotNull(zip.getEntry("Metadata/plate_1.json"))
            assertNotNull(zip.getEntry("Metadata/plate_1.gcode"))
            assertNotNull(zip.getEntry("Metadata/plate_1.gcode.md5"))
            assertNotNull(zip.getEntry("Metadata/plate_1.png"))
            assertNotNull(zip.getEntry("Metadata/plate_no_light_1.png"))
            assertNotNull(zip.getEntry("Metadata/plate_1_small.png"))
            assertNotNull(zip.getEntry("Metadata/filament_sequence.json"))
            assertNotNull(zip.getEntry("Metadata/slice_info.config"))
            val sliceInfo = zip.getInputStream(zip.getEntry("Metadata/slice_info.config"))
                .reader()
                .readText()
            assertTrue(sliceInfo.startsWith("<?xml version=\"1.0\""))
            val modelXml = zip.getInputStream(zip.getEntry("3D/3dmodel.model"))
                .reader()
                .readText()
            assertTrue(modelXml.contains("xmlns:BambuStudio"))
            assertTrue(modelXml.contains("<metadata name=\"BambuStudio:3mfVersion\">1</metadata>"))
            assertTrue(modelXml.contains("name=\"cube\""))
            assertTrue(modelXml.contains("p:path=\"/3D/Objects/object_1.model\""))
            val objectModelXml = zip.getInputStream(zip.getEntry("3D/Objects/object_1.model"))
                .reader()
                .readText()
            assertTrue(objectModelXml.contains("<vertices>"))
            assertTrue(objectModelXml.contains("<triangles>"))

            val cutInformation = zip.getInputStream(zip.getEntry("Metadata/cut_information.xml"))
                .reader()
                .readText()
            assertTrue(cutInformation.contains("<objects>"))
            assertTrue(cutInformation.contains("<object id=\"1\">"))
            assertTrue(cutInformation.contains("<cut_id id=\"0\""))

            val modelSettings = zip.getInputStream(zip.getEntry("Metadata/model_settings.config"))
                .reader()
                .readText()
            assertTrue(modelSettings.contains("plater_name"))
            assertTrue(modelSettings.contains("filament_maps"))
            assertTrue(modelSettings.contains("object_id"))
            assertTrue(modelSettings.contains("gcode_file"))
            assertTrue(modelSettings.contains("pattern_bbox_file"))

            val gcodeRelationship = zip.getInputStream(
                zip.getEntry("Metadata/_rels/model_settings.config.rels"),
            ).reader().readText()
            assertTrue(gcodeRelationship.contains("Metadata/plate_1.gcode"))
            assertTrue(gcodeRelationship.contains("package/2021/gcode"))

            val plateMetadata = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/plate_1.json")).reader().readText(),
            )
            assertEquals(0, plateMetadata.getJSONArray("filament_ids").getInt(0))
            assertEquals(1, plateMetadata.getJSONArray("bbox_objects").length())

            val projectSettings = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/project_settings.config"))
                    .reader()
                    .readText()
            )
            assertEquals("cube", projectSettings.getString("model_name"))
            assertEquals("#FFFFFF", projectSettings.getJSONArray("filament_colour").getString(0))
            assertEquals("PLA", projectSettings.getJSONArray("filament_type").getString(0))
            assertEquals("Bambu PLA Basic @BBL A1M", projectSettings.getJSONArray("filament_settings_id").getString(0))
            assertEquals("GFA00", projectSettings.getJSONArray("filament_ids").getString(0))
            assertEquals("N1", projectSettings.getString("printer_model_id"))
            assertEquals("Bambu Lab A1 mini", projectSettings.getString("printer_model"))
            assertEquals(4, projectSettings.getJSONArray("printable_area").length())
            assertEquals("180x180", projectSettings.getJSONArray("printable_area").getString(2))
            assertTrue(!projectSettings.has("bed_shape"))
            assertEquals("f87ed23d64dae001c49e38192e0fbd28", zip.getInputStream(
                zip.getEntry("Metadata/plate_1.gcode.md5")
            ).reader().readText().lowercase())
            assertTrue(
                zip.getInputStream(zip.getEntry("Metadata/plate_1.gcode"))
                    .reader()
                    .readText()
                    .contains("G28")
            )
            val sequence = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/filament_sequence.json")).reader().readText(),
            )
            assertEquals(1, sequence.getJSONObject("plate_1").getJSONArray("sequence").getInt(0))
        }
    }

    @Test
    fun `writer normalizes names and filament metadata for generated bambu projects`() {
        val gcode = tmp.newFile("plate_3.gcode").apply {
            writeText("; generated by test\nG28\n")
        }
        val out = File(tmp.root, "A1 Mini Preview.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "A1 Mini Preview.stl",
            plateId = 3,
            filamentColours = listOf("#abcdef12", "bad"),
            filamentTypes = listOf("PETG"),
        )

        ZipFile(out).use { zip ->
            val modelXml = zip.getInputStream(zip.getEntry("3D/3dmodel.model"))
                .reader()
                .readText()
            assertTrue(modelXml.contains("<metadata name=\"Title\">A1 Mini Preview</metadata>"))
            assertTrue(modelXml.contains("name=\"A1 Mini Preview\""))

            val modelSettings = zip.getInputStream(zip.getEntry("Metadata/model_settings.config"))
                .reader()
                .readText()
            assertTrue(modelSettings.contains("value=\"Plate 3 - A1 Mini Preview\""))
            assertTrue(modelSettings.contains("value=\"1 1\""))
            assertTrue(modelSettings.contains("value=\"1\""))

            val sliceInfo = zip.getInputStream(zip.getEntry("Metadata/slice_info.config"))
                .reader()
                .readText()
            assertTrue(sliceInfo.contains("filament_maps\" value=\"1 1\""))
            assertTrue(sliceInfo.contains("limit_filament_maps\" value=\"0 0\""))
            assertTrue(sliceInfo.contains("<object identify_id=\"1\" name=\"A1 Mini Preview\""))

            val projectSettings = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/project_settings.config"))
                    .reader()
                    .readText()
            )
            assertEquals("A1 Mini Preview", projectSettings.getString("model_name"))
            assertEquals("#ABCDEF", projectSettings.getJSONArray("filament_colour").getString(0))
            assertEquals("#FFFFFF", projectSettings.getJSONArray("filament_colour").getString(1))
            assertEquals("#ABCDEF", projectSettings.getJSONArray("extruder_colour").getString(0))
            assertEquals("PETG", projectSettings.getJSONArray("filament_type").getString(0))
            assertEquals("PLA", projectSettings.getJSONArray("filament_type").getString(1))
            assertEquals("Generic PETG", projectSettings.getJSONArray("filament_settings_id").getString(0))
            assertEquals("Bambu PLA Basic @BBL A1M", projectSettings.getJSONArray("filament_settings_id").getString(1))
            assertEquals("2", projectSettings.getString("filament_count"))
        }
    }

    @Test
    fun `writer carries the resolved gcode config and its large thumbnail into the project`() {
        val gcode = tmp.newFile("plate_1.gcode").apply {
            writeText(
                """
                ; thumbnail begin 300x300 68
                ; iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9swAAAABJRU5ErkJggg==
                ; thumbnail end
                ; CONFIG_BLOCK_START
                ; outer_wall_speed = 200
                ; CONFIG_BLOCK_END
                G28
                """.trimIndent(),
            )
        }
        val out = File(tmp.root, "a1-mini-project.gcode.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "cube",
            plateId = 1,
            filamentColours = listOf("#FFFFFF"),
            filamentTypes = listOf("PLA"),
        )

        ZipFile(out).use { zip ->
            val settings = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/project_settings.config")).reader().readText(),
            )
            assertEquals("200", settings.getString("outer_wall_speed"))
            assertTrue(zip.getInputStream(zip.getEntry("Metadata/plate_1.png")).readBytes().size > 20)
            val packagedGcode = zip.getInputStream(zip.getEntry("Metadata/plate_1.gcode"))
                .reader()
                .readText()
            assertTrue(packagedGcode.startsWith("; CONFIG_BLOCK_START"))
            assertTrue(!packagedGcode.contains("; thumbnail begin"))
        }
    }

    @Test
    fun `writer moves native eof config before executable block`() {
        val gcode = tmp.newFile("native-layout.gcode").apply {
            writeText(
                """
                ; HEADER_BLOCK_START
                ; generated by test
                ; HEADER_BLOCK_END
                ; thumbnail begin 1x1 4
                ; AAAA
                ; thumbnail end
                ; EXECUTABLE_BLOCK_START
                G28
                ; EXECUTABLE_BLOCK_END
                ; CONFIG_BLOCK_START
                ; printer_model = Bambu Lab A1 mini
                ; CONFIG_BLOCK_END
                """.trimIndent(),
            )
        }
        val out = File(tmp.root, "native-layout.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "cube",
            plateId = 1,
            filamentColours = listOf("#FFFFFF"),
            filamentTypes = listOf("PLA"),
        )

        ZipFile(out).use { zip ->
            val packaged = zip.getInputStream(zip.getEntry("Metadata/plate_1.gcode"))
                .reader()
                .readText()
            assertTrue(packaged.indexOf("; HEADER_BLOCK_END") < packaged.indexOf("; CONFIG_BLOCK_START"))
            assertTrue(packaged.indexOf("; CONFIG_BLOCK_END") < packaged.indexOf("; EXECUTABLE_BLOCK_START"))
            assertTrue(!packaged.contains("; thumbnail begin"))
            val expectedMd5 = java.security.MessageDigest.getInstance("MD5")
                .digest(packaged.toByteArray())
                .joinToString("") { "%02x".format(it) }
            assertEquals(
                expectedMd5,
                zip.getInputStream(zip.getEntry("Metadata/plate_1.gcode.md5"))
                    .reader()
                    .readText()
                    .lowercase(),
            )
        }
    }

    @Test
    fun `writer compacts sparse per filament settings and flush matrix`() {
        val gcode = tmp.newFile("sparse.gcode").apply {
            writeText(
                """
                ; CONFIG_BLOCK_START
                ; filament_density = 1.1,1.2,1.3,1.4
                ; nozzle_temperature = 200,210,220,230
                ; flush_volumes_matrix = 0,1,2,3,10,11,12,13,20,21,22,23,30,31,32,33
                ; machine_max_speed_x = 500,200
                ; CONFIG_BLOCK_END
                G28
                """.trimIndent(),
            )
        }
        val out = File(tmp.root, "sparse.gcode.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "sparse",
            plateId = 1,
            filamentColours = listOf("#222222", "#444444"),
            filamentTypes = listOf("PETG", "TPU"),
            sourceFilamentIndices = listOf(1, 3),
        )

        ZipFile(out).use { zip ->
            val settings = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/project_settings.config")).reader().readText(),
            )
            assertEquals(listOf("1.2", "1.4"), settings.getJSONArray("filament_density").toStringList())
            assertEquals(listOf("210", "230"), settings.getJSONArray("nozzle_temperature").toStringList())
            assertEquals(listOf("11", "13", "31", "33"), settings.getJSONArray("flush_volumes_matrix").toStringList())
            assertEquals("500,200", settings.getString("machine_max_speed_x"))
        }
    }

    @Test
    fun `writer records real sliced bounds time and filament usage`() {
        val gcode = tmp.newFile("measured.gcode").apply {
            writeText(
                """
                ; max_z_height: 10.00
                ; CONFIG_BLOCK_START
                ; layer_height = 0.2
                ; curr_bed_type = Textured PEI Plate
                ; CONFIG_BLOCK_END
                EXCLUDE_OBJECT_DEFINE NAME=cube CENTER=90,90 POLYGON=[[85,85],[95,85],[95,95],[85,95]]
                ;LAYER_CHANGE
                G0 X84 Y84
                G1 X96 Y84 E0.5
                G1 X96 Y96 E0.5
                ;LAYER_CHANGE
                ; filament used [mm] = 4241.66
                ; filament used [g] = 12.85
                ; estimated printing time (normal mode) = 1h 44m 23s
                """.trimIndent(),
            )
        }
        val out = File(tmp.root, "measured.gcode.3mf")

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "cube",
            plateId = 1,
            filamentColours = listOf("#FFFFFF"),
            filamentTypes = listOf("PLA"),
        )

        ZipFile(out).use { zip ->
            val plate = JSONObject(
                zip.getInputStream(zip.getEntry("Metadata/plate_1.json")).reader().readText(),
            )
            assertEquals(84.0, plate.getJSONArray("bbox_all").getDouble(0), 0.0001)
            assertEquals(96.0, plate.getJSONArray("bbox_all").getDouble(3), 0.0001)
            assertEquals("textured_plate", plate.getString("bed_type"))
            assertTrue(plate.getJSONArray("bbox_objects").getJSONObject(0).getDouble("area") > 0.0)

            val sliceInfo = zip.getInputStream(zip.getEntry("Metadata/slice_info.config"))
                .reader().readText()
            assertTrue(sliceInfo.contains("key=\"prediction\" value=\"6263\""))
            assertTrue(sliceInfo.contains("key=\"weight\" value=\"12.85\""))
            assertTrue(sliceInfo.contains("used_m=\"4.2417\""))
            assertTrue(sliceInfo.contains("used_g=\"12.85\""))

            val model = zip.getInputStream(zip.getEntry("3D/3dmodel.model")).reader().readText()
            assertTrue(model.contains(" 90 90 0\" printable=\"1\""))
            val objectModel = zip.getInputStream(zip.getEntry("3D/Objects/object_1.model"))
                .reader().readText()
            assertTrue(objectModel.contains("x=\"-5\""))
            assertTrue(objectModel.contains("z=\"10\""))
        }
    }

    @Test
    fun `writer atomically replaces an existing project and removes staging file`() {
        val gcode = tmp.newFile("atomic.gcode").apply { writeText("G28\n") }
        val out = File(tmp.root, "atomic.gcode.3mf").apply { writeText("old-incomplete-project") }

        BambuProjectWriter.writeSinglePlateProject(
            outputFile = out,
            gcodeFile = gcode,
            modelName = "atomic",
            plateId = 1,
            filamentColours = listOf("#FFFFFF"),
            filamentTypes = listOf("PLA"),
        )

        ZipFile(out).use { zip ->
            assertNotNull(zip.getEntry("Metadata/plate_1.gcode"))
        }
        assertTrue(
            tmp.root.listFiles().orEmpty().none {
                it.name.startsWith(".${out.name}.") && it.name.endsWith(".tmp")
            },
        )
    }

    private fun org.json.JSONArray.toStringList(): List<String> =
        List(length()) { index -> getString(index) }
}
