package com.u1.slicer.gcode

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * Instrumented tests for GcodeThumbnailInjector.
 *
 * Uses real 3MF assets to test image extraction, thumbnail block building,
 * and G-code injection. Requires device because of android.graphics.Bitmap.
 */
@RunWith(AndroidJUnit4::class)
class GcodeThumbnailInjectorTest {

    private lateinit var cacheDir: File
    private lateinit var threeMfFile: File

    @Before
    fun setUp() {
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        cacheDir = File(ctx.cacheDir, "thumbnail_test").apply { mkdirs() }

        // Copy 3MF asset to a temp file (ZipFile needs a real file path)
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        threeMfFile = File(cacheDir, "fan-cover.3mf")
        assets.open("u1-auxiliary-fan-cover-hex_mw.3mf").use { input ->
            threeMfFile.outputStream().use { output -> input.copyTo(output) }
        }
    }

    @After
    fun tearDown() {
        cacheDir.deleteRecursively()
    }

    @Test
    fun extractPreviewImage_returns_bitmap_from_3mf() {
        val bitmap = GcodeThumbnailInjector.extractPreviewImage(threeMfFile)
        assertNotNull("Should extract a preview image from 3MF", bitmap)
        assertTrue("Bitmap width > 0", bitmap!!.width > 0)
        assertTrue("Bitmap height > 0", bitmap.height > 0)
    }

    @Test
    fun extractPreviewImage_returns_null_for_non_3mf() {
        val txtFile = File(cacheDir, "dummy.txt").apply { writeText("hello") }
        val bitmap = GcodeThumbnailInjector.extractPreviewImage(txtFile)
        assertNull("Non-ZIP file should return null", bitmap)
    }

    @Test
    fun buildThumbnailBlocks_contains_both_sizes() {
        val bitmap = GcodeThumbnailInjector.extractPreviewImage(threeMfFile)!!
        val blocks = GcodeThumbnailInjector.buildThumbnailBlocks(bitmap)

        assertTrue("Should contain 48x48 thumbnail", blocks.contains("; thumbnail begin 48x48"))
        assertTrue("Should contain 300x300 thumbnail", blocks.contains("; thumbnail begin 300x300"))
        assertTrue("Should contain thumbnail end markers", blocks.contains("; thumbnail end"))
        assertFalse("Should NOT contain THUMBNAIL_BLOCK_START wrappers", blocks.contains("; THUMBNAIL_BLOCK_START"))

        // Count exactly 2 begin/end pairs
        val beginCount = "; thumbnail begin".toRegex().findAll(blocks).count()
        val endCount = "; thumbnail end".toRegex().findAll(blocks).count()
        assertEquals("Should have 2 thumbnail begin markers", 2, beginCount)
        assertEquals("Should have 2 thumbnail end markers", 2, endCount)
    }

    @Test
    fun buildThumbnailBlocks_lines_are_commented() {
        val bitmap = GcodeThumbnailInjector.extractPreviewImage(threeMfFile)!!
        val blocks = GcodeThumbnailInjector.buildThumbnailBlocks(bitmap)

        for (line in blocks.lines()) {
            if (line.isNotEmpty()) {
                assertTrue("Every line should start with ';' or '; ': $line", line == ";" || line.startsWith("; "))
            }
        }
    }

    @Test
    fun inject_inserts_after_header_block_end() {
        val gcodeFile = File(cacheDir, "test.gcode")
        gcodeFile.writeText(
            """; generated by test
; HEADER_BLOCK_END
G28
G1 X10 Y10
"""
        )

        val result = GcodeThumbnailInjector.inject(gcodeFile.absolutePath, threeMfFile.absolutePath)
        assertTrue("inject() should return true", result)

        val content = gcodeFile.readText()
        val headerEndPos = content.indexOf("; HEADER_BLOCK_END")
        val thumbnailPos = content.indexOf("; thumbnail begin")
        val g28Pos = content.indexOf("G28")

        assertTrue("Thumbnail should exist", thumbnailPos >= 0)
        assertTrue("Thumbnail should be after HEADER_BLOCK_END", thumbnailPos > headerEndPos)
        assertTrue("Thumbnail should be before G28", thumbnailPos < g28Pos)
    }

    @Test
    fun inject_prepends_when_no_header_block_end() {
        val gcodeFile = File(cacheDir, "test_noheader.gcode")
        gcodeFile.writeText("G28\nG1 X10 Y10\n")

        val result = GcodeThumbnailInjector.inject(gcodeFile.absolutePath, threeMfFile.absolutePath)
        assertTrue("inject() should return true", result)

        val content = gcodeFile.readText()
        assertTrue("Should start with thumbnail begin (no wrapper)", content.startsWith("; thumbnail begin 48x48"))
        assertTrue("Should contain 300x300 thumbnail", content.contains("; thumbnail begin 300x300"))
    }

    @Test
    fun inject_returns_false_for_non_3mf_source() {
        val gcodeFile = File(cacheDir, "test.gcode")
        gcodeFile.writeText("G28\n")

        val stlFile = File(cacheDir, "model.stl")
        stlFile.writeText("solid test\nendsolid test\n")

        val result = GcodeThumbnailInjector.inject(gcodeFile.absolutePath, stlFile.absolutePath)
        assertFalse("inject() should return false for .stl source", result)
    }

    @Test
    fun inject_returns_false_for_missing_source() {
        val gcodeFile = File(cacheDir, "test.gcode")
        gcodeFile.writeText("G28\n")

        val result = GcodeThumbnailInjector.inject(gcodeFile.absolutePath, "/nonexistent/model.3mf")
        assertFalse("inject() should return false for missing source", result)
    }
}
