package com.u1.slicer

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.u1.slicer.data.SliceJob
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * B40: Verifies that loadJobGcodeForViewer() transitions the ViewModel state to SliceComplete
 * after kill+reopen so the Preview tab renders the G-code viewer instead of "No slice results".
 */
@RunWith(AndroidJUnit4::class)
class LoadJobGcodeViewModelTest {

    private val targetContext get() = InstrumentationRegistry.getInstrumentation().targetContext

    // Regression: B40 — loadJobGcodeForViewer previously set _parsedGcode but left _state = Idle,
    // causing Preview tab to show "No slice results" after kill+reopen
    @Test
    fun loadJobGcodeForViewer_setsSliceCompleteState_notIdle() {
        val application = targetContext.applicationContext as U1SlicerApplication
        val viewModel = SlicerViewModel(application)

        // Write minimal valid G-code to a temp file
        val gcodeFile = File(targetContext.cacheDir, "b40_test.gcode")
        gcodeFile.writeText(
            "; Generated by U1 Slicer\n" +
            "G28 ; home\n" +
            "G1 Z0.2 F3000\n" +
            "; LAYER_CHANGE\n" +
            ";LAYER_NUM:0\n" +
            "G1 X10 Y10 E1.0 F1500\n" +
            "M104 S0\n" +
            "M140 S0\n"
        )

        val job = SliceJob(
            id = 99L,
            modelName = "b40_test.stl",
            gcodePath = gcodeFile.absolutePath,
            sourcePath = null,
            totalLayers = 1,
            estimatedTimeSeconds = 60f,
            estimatedFilamentMm = 100f,
            estimatedFilamentGrams = 0f,
            layerHeight = 0.2f,
            fillDensity = 15f,
            nozzleTemp = 200,
            bedTemp = 60,
            supportEnabled = false,
            filamentType = "PLA"
        )

        val latch = CountDownLatch(1)
        var callbackSuccess = false

        try {
            viewModel.loadJobGcodeForViewer(job) { success ->
                callbackSuccess = success
                latch.countDown()
            }

            val completed = latch.await(10, TimeUnit.SECONDS)
            assertTrue("loadJobGcodeForViewer callback timed out", completed)
            assertTrue("loadJobGcodeForViewer callback reported failure", callbackSuccess)
            assertTrue(
                "state should be SliceComplete after loadJobGcodeForViewer, was ${viewModel.state.value}",
                viewModel.state.value is SlicerViewModel.SlicerState.SliceComplete
            )
            val result = (viewModel.state.value as SlicerViewModel.SlicerState.SliceComplete).result
            assertEquals(gcodeFile.absolutePath, result.gcodePath)
        } finally {
            gcodeFile.delete()
        }
    }
}
